"use client";

import { useState } from "react";
import { useMonturas } from "../../../hooks/useMonturas";
import MonturaGrid from "../../../components/monturas/MonturaGrid";
import { useAuth } from "../../../hooks/useAuth";
import { Glasses, SlidersHorizontal, Loader2, Plus, X, Tag, DollarSign, Layers, Eye } from "lucide-react";

export default function MonturasPage() {
  const [genderFilter, setGenderFilter] = useState<string>("");
  const [colorFilter, setColorFilter] = useState<string>("");
  const [stockFilter, setStockFilter] = useState<boolean | undefined>(undefined);
  
  // Modal State
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [nombreMontura, setNombreMontura] = useState("");
  const [idMaterial, setIdMaterial] = useState("1");
  const [colorMontura, setColorMontura] = useState("Negro");
  const [generoMontura, setGeneroMontura] = useState("Unisex");
  const [stockMontura, setStockMontura] = useState("15");
  const [precioMontura, setPrecioMontura] = useState("189900");
  const [formError, setFormError] = useState<string | null>(null);

  const { useGetMonturas, adjustStockMutation, createMonturaMutation } = useMonturas();
  const { user } = useAuth();
  
  const isAdmin = user?.rol === "administrador";

  const filters = {
    ...(genderFilter && { gender: genderFilter }),
    ...(colorFilter && { color: colorFilter }),
    ...(stockFilter !== undefined && { has_stock: stockFilter }),
  };

  const { data: monturas = [], isLoading, isError, refetch } = useGetMonturas(filters);

  const handleAdjustStock = async (id: number, stock: number) => {
    try {
      await adjustStockMutation.mutateAsync({ id, stock });
    } catch (err) {
      alert(err instanceof Error ? err.message : "Error al ajustar stock");
    }
  };

  const handleCreateMontura = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!nombreMontura || !precioMontura || !stockMontura) {
      setFormError("Por favor completa los campos obligatorios");
      return;
    }

    setFormError(null);
    try {
      await createMonturaMutation.mutateAsync({
        idMontura: 0, // autogenerated by backend
        nombreMontura,
        idMaterial: Number(idMaterial),
        colorMontura,
        generoMontura,
        stockMontura: Number(stockMontura),
        precioMontura: Number(precioMontura),
        imagenMontura: "classic_oval.png" // default placeholder image name
      });
      
      // Reset & Close
      setNombreMontura("");
      setIdMaterial("1");
      setColorMontura("Negro");
      setGeneroMontura("Unisex");
      setStockMontura("15");
      setPrecioMontura("189900");
      setIsModalOpen(false);
    } catch (err) {
      setFormError(err instanceof Error ? err.message : "Error al registrar montura");
    }
  };

  // Materials dropdown map
  const materials = [
    { id: 1, name: "Acetato" },
    { id: 2, name: "Metal" },
    { id: 3, name: "Titanio" },
    { id: 4, name: "TR90" },
    { id: 5, name: "Madera" },
    { id: 6, name: "Aluminio" },
    { id: 7, name: "Acero inoxidable" },
    { id: 8, name: "Fibra de carbono" },
    { id: 9, name: "Nylon" },
    { id: 10, name: "Policarbonato" },
  ];

  return (
    <div className="space-y-6 relative">
      {/* Header and subtitle */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-extrabold text-slate-100 flex items-center gap-2">
            <Glasses className="w-7 h-7 text-indigo-400" />
            Catálogo de Monturas
          </h1>
          <p className="text-xs text-slate-400 mt-1">
            Explora monturas por material, color y género, y gestiona niveles de inventario físico.
          </p>
        </div>

        {/* Admin Frame Addition Trigger Button */}
        {isAdmin && (
          <button
            onClick={() => { setIsModalOpen(true); setFormError(null); }}
            className="glow-btn bg-gradient-to-r from-indigo-600 to-purple-600 hover:from-indigo-500 hover:to-purple-500 text-white font-bold text-xs px-4 py-3 rounded-xl shadow-xl shadow-indigo-600/10 flex items-center gap-2 transition-all shrink-0 active:scale-95"
          >
            <Plus className="w-4 h-4 text-white" />
            Agregar Montura
          </button>
        )}
      </div>

      {/* Modern custom filter panel */}
      <div className="glass-panel rounded-2xl border border-slate-800/60 p-5 bg-slate-900/30 flex flex-wrap items-center gap-6">
        <div className="flex items-center gap-2 text-xs font-bold text-slate-400 uppercase tracking-wider font-mono">
          <SlidersHorizontal className="w-4 h-4 text-indigo-400" />
          Filtros
        </div>

        {/* Gender Filter */}
        <div className="flex flex-col gap-1.5">
          <span className="text-[9px] font-bold text-slate-500 uppercase tracking-wider">Género</span>
          <select
            value={genderFilter}
            onChange={(e) => setGenderFilter(e.target.value)}
            className="bg-slate-950 border border-slate-800 rounded-xl px-3 py-1.5 text-xs text-slate-300 focus:outline-none focus:border-indigo-500/50"
          >
            <option value="">Todos</option>
            <option value="Unisex">Unisex</option>
            <option value="Hombre">Hombre</option>
            <option value="Mujer">Mujer</option>
          </select>
        </div>

        {/* Color Filter */}
        <div className="flex flex-col gap-1.5">
          <span className="text-[9px] font-bold text-slate-500 uppercase tracking-wider">Color del Marco</span>
          <select
            value={colorFilter}
            onChange={(e) => setColorFilter(e.target.value)}
            className="bg-slate-950 border border-slate-800 rounded-xl px-3 py-1.5 text-xs text-slate-300 focus:outline-none focus:border-indigo-500/50"
          >
            <option value="">Todos</option>
            <option value="Negro">Negro</option>
            <option value="Dorado">Dorado</option>
            <option value="Plata">Plata</option>
            <option value="Azul">Azul</option>
            <option value="Cafe">Café</option>
            <option value="Rojo">Rojo</option>
            <option value="Verde">Verde</option>
          </select>
        </div>

        {/* Stock Filter */}
        <div className="flex flex-col gap-1.5">
          <span className="text-[9px] font-bold text-slate-500 uppercase tracking-wider">Inventario</span>
          <select
            value={stockFilter === undefined ? "" : stockFilter ? "true" : "false"}
            onChange={(e) => {
              const val = e.target.value;
              if (val === "") setStockFilter(undefined);
              else setStockFilter(val === "true");
            }}
            className="bg-slate-950 border border-slate-800 rounded-xl px-3 py-1.5 text-xs text-slate-300 focus:outline-none focus:border-indigo-500/50"
          >
            <option value="">Todos</option>
            <option value="true">En Stock</option>
          </select>
        </div>
      </div>

      {/* Main content grid */}
      {isLoading ? (
        <div className="h-64 flex flex-col items-center justify-center text-slate-500">
          <Loader2 className="w-8 h-8 text-indigo-500 animate-spin mb-3" />
          <p className="text-xs">Cargando catálogo de monturas...</p>
        </div>
      ) : isError ? (
        <div className="glass-panel rounded-2xl border border-rose-500/25 p-8 text-center text-rose-400">
          <p className="text-xs">Ocurrió un error al intentar cargar el catálogo. Por favor comprueba tu conexión.</p>
        </div>
      ) : (
        <MonturaGrid 
          monturas={monturas} 
          onAdjustStock={handleAdjustStock}
          isAdjusting={adjustStockMutation.isPending}
          isAdmin={isAdmin}
        />
      )}

      {/* MODAL DIALOG: Registrar Nueva Montura */}
      {isModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
          {/* Backdrop */}
          <div 
            onClick={() => setIsModalOpen(false)}
            className="absolute inset-0 bg-slate-950/70 backdrop-blur-sm animate-in fade-in duration-200"
          />
          
          {/* Modal Box */}
          <div className="w-full max-w-md bg-slate-900/40 border border-slate-800/80 backdrop-blur-2xl rounded-3xl p-6 shadow-2xl z-10 animate-in zoom-in-95 duration-200 relative overflow-hidden">
            <div className="absolute top-0 right-0 w-32 h-32 bg-indigo-500/5 rounded-full blur-2xl pointer-events-none select-none"></div>

            {/* Header */}
            <div className="flex items-center justify-between pb-4 border-b border-slate-800/40 mb-5">
              <div className="flex items-center gap-2">
                <div className="w-8 h-8 rounded-xl bg-gradient-to-tr from-indigo-500 to-purple-600 flex items-center justify-center shadow-lg">
                  <Glasses className="w-4 h-4 text-white" />
                </div>
                <h3 className="font-bold text-slate-100 text-sm tracking-wide">Nueva Montura</h3>
              </div>
              <button 
                onClick={() => setIsModalOpen(false)}
                className="p-1.5 rounded-lg bg-slate-850 hover:bg-slate-800 text-slate-400 hover:text-slate-200 transition-colors"
              >
                <X className="w-4 h-4" />
              </button>
            </div>

            {/* Form Error */}
            {formError && (
              <div className="bg-rose-500/10 border border-rose-500/25 px-3 py-2 rounded-xl text-[11px] text-rose-400 mb-4 font-semibold flex items-center gap-2">
                <span className="w-1.5 h-1.5 bg-rose-400 rounded-full animate-ping shrink-0"></span>
                {formError}
              </div>
            )}

            {/* Modal Form */}
            <form onSubmit={handleCreateMontura} className="space-y-4">
              
              {/* Name */}
              <div className="space-y-1">
                <label className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">Nombre de Montura *</label>
                <input
                  type="text"
                  required
                  placeholder="Ej. Classic Aviator"
                  value={nombreMontura}
                  onChange={(e) => setNombreMontura(e.target.value)}
                  className="w-full bg-slate-950/80 border border-slate-800 rounded-xl px-3.5 py-2.5 text-xs text-slate-200 focus:outline-none focus:border-indigo-500/50 transition-all placeholder-slate-700"
                />
              </div>

              {/* Material Dropdown */}
              <div className="space-y-1">
                <label className="text-[10px] font-bold text-slate-400 uppercase tracking-wider flex items-center gap-1">
                  <Layers className="w-3 h-3 text-indigo-400" />
                  Material *
                </label>
                <select
                  value={idMaterial}
                  onChange={(e) => setIdMaterial(e.target.value)}
                  className="w-full bg-slate-950/80 border border-slate-800 rounded-xl px-3.5 py-2.5 text-xs text-slate-350 focus:outline-none focus:border-indigo-500/50"
                >
                  {materials.map((m) => (
                    <option key={m.id} value={m.id}>{m.name}</option>
                  ))}
                </select>
              </div>

              {/* Color & Gender */}
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-1">
                  <label className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">Color *</label>
                  <select
                    value={colorMontura}
                    onChange={(e) => setColorMontura(e.target.value)}
                    className="w-full bg-slate-950/80 border border-slate-800 rounded-xl px-3 py-2.5 text-xs text-slate-300 focus:outline-none focus:border-indigo-500/50"
                  >
                    <option value="Negro">Negro</option>
                    <option value="Dorado">Dorado</option>
                    <option value="Plata">Plata</option>
                    <option value="Azul">Azul</option>
                    <option value="Cafe">Café</option>
                    <option value="Rojo">Rojo</option>
                    <option value="Verde">Verde</option>
                  </select>
                </div>

                <div className="space-y-1">
                  <label className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">Género *</label>
                  <select
                    value={generoMontura}
                    onChange={(e) => setGeneroMontura(e.target.value)}
                    className="w-full bg-slate-950/80 border border-slate-800 rounded-xl px-3 py-2.5 text-xs text-slate-300 focus:outline-none focus:border-indigo-500/50"
                  >
                    <option value="Unisex">Unisex</option>
                    <option value="Hombre">Hombre</option>
                    <option value="Mujer">Mujer</option>
                  </select>
                </div>
              </div>

              {/* Stock & Price */}
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-1">
                  <label className="text-[10px] font-bold text-slate-400 uppercase tracking-wider flex items-center gap-1">
                    <Tag className="w-3 h-3 text-indigo-400" />
                    Stock Inicial *
                  </label>
                  <input
                    type="number"
                    required
                    min="0"
                    placeholder="15"
                    value={stockMontura}
                    onChange={(e) => setStockMontura(e.target.value)}
                    className="w-full bg-slate-950/80 border border-slate-800 rounded-xl px-3.5 py-2.5 text-xs text-slate-200 focus:outline-none focus:border-indigo-500/50"
                  />
                </div>

                <div className="space-y-1">
                  <label className="text-[10px] font-bold text-slate-400 uppercase tracking-wider flex items-center gap-1">
                    <DollarSign className="w-3 h-3 text-indigo-400" />
                    Precio ($ COP) *
                  </label>
                  <input
                    type="number"
                    required
                    min="1"
                    placeholder="189900"
                    value={precioMontura}
                    onChange={(e) => setPrecioMontura(e.target.value)}
                    className="w-full bg-slate-950/80 border border-slate-800 rounded-xl px-3.5 py-2.5 text-xs text-slate-200 focus:outline-none focus:border-indigo-500/50"
                  />
                </div>
              </div>

              {/* Submit */}
              <button
                type="submit"
                disabled={createMonturaMutation.isPending}
                className="glow-btn w-full py-3.5 rounded-xl bg-gradient-to-r from-indigo-600 to-purple-600 hover:from-indigo-500 hover:to-purple-500 text-white font-bold text-xs shadow-xl shadow-indigo-600/10 flex items-center justify-center gap-2 group transition-all mt-2 active:scale-98"
              >
                {createMonturaMutation.isPending ? (
                  <Loader2 className="w-4 h-4 animate-spin text-white" />
                ) : (
                  <>
                    <Plus className="w-4 h-4 text-white" />
                    Registrar en Catálogo
                  </>
                )}
              </button>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
