"use client";

import { useState } from "react";
import { useAuth } from "../../hooks/useAuth";
import { Eye, Shield, Users, LogIn, UserPlus, AlertCircle, Sparkles } from "lucide-react";

export default function LoginPage() {
  const [isLogin, setIsLogin] = useState(true);
  const { login, register } = useAuth();
  
  // Login Form States
  const [loginEmail, setLoginEmail] = useState("");
  const [loginPassword, setLoginPassword] = useState("");
  
  // Register Form States
  const [primerNombre, setPrimerNombre] = useState("");
  const [segundoNombre, setSegundoNombre] = useState("");
  const [primerApellido, setPrimerApellido] = useState("");
  const [segundoApellido, setSegundoApellido] = useState("");
  const [registerEmail, setRegisterEmail] = useState("");
  const [registerPassword, setRegisterPassword] = useState("");
  const [fechaNacimiento, setFechaNacimiento] = useState("");
  const [direccion, setDireccion] = useState("");

  // Error and Loading States
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  // Quick Login Helpers
  const handleQuickLogin = async (role: "admin" | "client") => {
    setError(null);
    setLoading(true);
    try {
      if (role === "admin") {
        await login({ correoUsuario: "admin@optilook.com", contrasena: "admin" });
      } else {
        await login({ correoUsuario: "ana.gomez@example.com", contrasena: "1234567890" });
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : "Error al iniciar sesión");
    } finally {
      setLoading(false);
    }
  };

  const handleLoginSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!loginEmail || !loginPassword) {
      setError("Por favor completa todos los campos");
      return;
    }
    setError(null);
    setLoading(true);
    try {
      await login({ correoUsuario: loginEmail, contrasena: loginPassword });
    } catch (err) {
      setError(err instanceof Error ? err.message : "Error al iniciar sesión");
    } finally {
      setLoading(false);
    }
  };

  const handleRegisterSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!primerNombre || !primerApellido || !registerEmail || !registerPassword || !fechaNacimiento || !direccion) {
      setError("Por favor completa los campos obligatorios (*)");
      return;
    }
    setError(null);
    setLoading(true);
    try {
      await register({
        idUsuario: 0, // Auto-generated by backend
        primerNombre,
        segundoNombre: segundoNombre || "",
        primerApellido,
        segundoApellido: segundoApellido || "",
        correoUsuario: registerEmail,
        fechaNacimiento,
        direccion,
        contrasena: registerPassword,
        rol: "cliente"
      });
    } catch (err) {
      setError(err instanceof Error ? err.message : "Error al registrarse");
    } finally {
      setLoading(false);
    }
  };

  return (
    <main className="min-h-screen bg-slate-950 text-slate-100 flex flex-col items-center justify-center p-4 md:p-6 relative overflow-hidden font-sans">
      {/* Background Neon Glowing Orbs */}
      <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-indigo-500/10 rounded-full blur-3xl -translate-x-1/2 -translate-y-1/2 select-none pointer-events-none"></div>
      <div className="absolute bottom-1/4 right-1/4 w-96 h-96 bg-purple-500/10 rounded-full blur-3xl translate-x-1/2 translate-y-1/2 select-none pointer-events-none"></div>

      <div className="w-full max-w-lg z-10 space-y-6">
        {/* Brand Header */}
        <div className="text-center space-y-2">
          <div className="inline-flex w-14 h-14 rounded-2xl bg-gradient-to-tr from-indigo-500 to-purple-600 items-center justify-center shadow-xl shadow-indigo-500/10 mb-2">
            <Eye className="w-8 h-8 text-white" />
          </div>
          <h1 className="text-3xl font-extrabold tracking-tight bg-gradient-to-r from-white via-slate-200 to-slate-400 bg-clip-text text-transparent">
            OptiLook Suite
          </h1>
          <p className="text-xs text-slate-400 max-w-sm mx-auto">
            Plataforma Inteligente de Diagnóstico Geométrico de Rostro y Gestión de Monturas.
          </p>
        </div>

        {/* Auth Box */}
        <div className="glass-panel border border-slate-800/80 rounded-3xl shadow-2xl p-6 md:p-8 bg-slate-900/20 backdrop-blur-2xl space-y-6">
          
          {/* Tab Selector */}
          <div className="grid grid-cols-2 p-1 bg-slate-950/80 rounded-2xl border border-slate-850">
            <button
              onClick={() => { setIsLogin(true); setError(null); }}
              className={`flex items-center justify-center gap-2 py-2.5 rounded-xl text-xs font-bold transition-all ${
                isLogin 
                  ? "bg-gradient-to-r from-indigo-600 to-purple-600 text-white shadow-lg" 
                  : "text-slate-400 hover:text-slate-200"
              }`}
            >
              <LogIn className="w-3.5 h-3.5" />
              Iniciar Sesión
            </button>
            <button
              onClick={() => { setIsLogin(false); setError(null); }}
              className={`flex items-center justify-center gap-2 py-2.5 rounded-xl text-xs font-bold transition-all ${
                !isLogin 
                  ? "bg-gradient-to-r from-indigo-600 to-purple-600 text-white shadow-lg" 
                  : "text-slate-400 hover:text-slate-200"
              }`}
            >
              <UserPlus className="w-3.5 h-3.5" />
              Crear Cuenta
            </button>
          </div>

          {/* Error Message */}
          {error && (
            <div className="bg-rose-500/10 border border-rose-500/25 px-4 py-3 rounded-2xl flex items-start gap-2.5 text-xs text-rose-400 animate-in fade-in slide-in-from-top-1 duration-200">
              <AlertCircle className="w-4 h-4 mt-0.5 shrink-0" />
              <p className="font-semibold leading-relaxed">{error}</p>
            </div>
          )}

          {/* Forms */}
          {isLogin ? (
            /* LOGIN FORM */
            <form onSubmit={handleLoginSubmit} className="space-y-4 animate-in fade-in duration-350">
              <div className="space-y-1">
                <label className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">Correo Electrónico</label>
                <input
                  type="email"
                  required
                  placeholder="ejemplo@optilook.com"
                  value={loginEmail}
                  onChange={(e) => setLoginEmail(e.target.value)}
                  className="w-full bg-slate-950/80 border border-slate-800 rounded-xl px-4 py-3 text-xs text-slate-200 focus:outline-none focus:border-indigo-500/50 focus:ring-1 focus:ring-indigo-500/20 placeholder-slate-600 transition-all"
                />
              </div>

              <div className="space-y-1">
                <label className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">Contraseña</label>
                <input
                  type="password"
                  required
                  placeholder="••••••••"
                  value={loginPassword}
                  onChange={(e) => setLoginPassword(e.target.value)}
                  className="w-full bg-slate-950/80 border border-slate-800 rounded-xl px-4 py-3 text-xs text-slate-200 focus:outline-none focus:border-indigo-500/50 focus:ring-1 focus:ring-indigo-500/20 placeholder-slate-600 transition-all"
                />
              </div>

              <button
                type="submit"
                disabled={loading}
                className="glow-btn w-full py-3.5 rounded-xl bg-gradient-to-r from-indigo-600 to-purple-600 hover:from-indigo-500 hover:to-purple-500 text-white font-bold text-xs shadow-xl shadow-indigo-600/10 flex items-center justify-center gap-2 group transition-all"
              >
                {loading ? (
                  <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
                ) : (
                  <>
                    <LogIn className="w-3.5 h-3.5" />
                    Ingresar al Panel
                  </>
                )}
              </button>
            </form>
          ) : (
            /* REGISTER FORM */
            <form onSubmit={handleRegisterSubmit} className="space-y-4 animate-in fade-in duration-350 max-h-[50vh] overflow-y-auto pr-1 select-none scrollbar-thin">
              
              {/* Names */}
              <div className="grid grid-cols-2 gap-3">
                <div className="space-y-1">
                  <label className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">Primer Nombre *</label>
                  <input
                    type="text"
                    required
                    placeholder="Ana"
                    value={primerNombre}
                    onChange={(e) => setPrimerNombre(e.target.value)}
                    className="w-full bg-slate-950/80 border border-slate-800 rounded-xl px-3.5 py-2.5 text-xs text-slate-200 focus:outline-none focus:border-indigo-500/50 placeholder-slate-650 transition-all"
                  />
                </div>
                <div className="space-y-1">
                  <label className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">Segundo Nombre</label>
                  <input
                    type="text"
                    placeholder="Lucía"
                    value={segundoNombre}
                    onChange={(e) => setSegundoNombre(e.target.value)}
                    className="w-full bg-slate-950/80 border border-slate-800 rounded-xl px-3.5 py-2.5 text-xs text-slate-200 focus:outline-none focus:border-indigo-500/50 placeholder-slate-650 transition-all"
                  />
                </div>
              </div>

              {/* Surnames */}
              <div className="grid grid-cols-2 gap-3">
                <div className="space-y-1">
                  <label className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">Primer Apellido *</label>
                  <input
                    type="text"
                    required
                    placeholder="Gómez"
                    value={primerApellido}
                    onChange={(e) => setPrimerApellido(e.target.value)}
                    className="w-full bg-slate-950/80 border border-slate-800 rounded-xl px-3.5 py-2.5 text-xs text-slate-200 focus:outline-none focus:border-indigo-500/50 placeholder-slate-650 transition-all"
                  />
                </div>
                <div className="space-y-1">
                  <label className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">Segundo Apellido</label>
                  <input
                    type="text"
                    placeholder="Pérez"
                    value={segundoApellido}
                    onChange={(e) => setSegundoApellido(e.target.value)}
                    className="w-full bg-slate-950/80 border border-slate-800 rounded-xl px-3.5 py-2.5 text-xs text-slate-200 focus:outline-none focus:border-indigo-500/50 placeholder-slate-650 transition-all"
                  />
                </div>
              </div>

              {/* Email */}
              <div className="space-y-1">
                <label className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">Correo Electrónico *</label>
                <input
                  type="email"
                  required
                  placeholder="correo@ejemplo.com"
                  value={registerEmail}
                  onChange={(e) => setRegisterEmail(e.target.value)}
                  className="w-full bg-slate-950/80 border border-slate-800 rounded-xl px-4 py-2.5 text-xs text-slate-200 focus:outline-none focus:border-indigo-500/50 placeholder-slate-650 transition-all"
                />
              </div>

              {/* Password */}
              <div className="space-y-1">
                <label className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">Contraseña *</label>
                <input
                  type="password"
                  required
                  placeholder="Crea una contraseña"
                  value={registerPassword}
                  onChange={(e) => setRegisterPassword(e.target.value)}
                  className="w-full bg-slate-950/80 border border-slate-800 rounded-xl px-4 py-2.5 text-xs text-slate-200 focus:outline-none focus:border-indigo-500/50 placeholder-slate-650 transition-all"
                />
              </div>

              {/* Birth Date and Address */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                <div className="space-y-1">
                  <label className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">Fecha de Nacimiento *</label>
                  <input
                    type="date"
                    required
                    value={fechaNacimiento}
                    onChange={(e) => setFechaNacimiento(e.target.value)}
                    className="w-full bg-slate-950/80 border border-slate-800 rounded-xl px-3.5 py-2.5 text-xs text-slate-200 focus:outline-none focus:border-indigo-500/50 transition-all"
                  />
                </div>
                <div className="space-y-1">
                  <label className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">Dirección *</label>
                  <input
                    type="text"
                    required
                    placeholder="Calle 10 # 15-20"
                    value={direccion}
                    onChange={(e) => setDireccion(e.target.value)}
                    className="w-full bg-slate-950/80 border border-slate-800 rounded-xl px-3.5 py-2.5 text-xs text-slate-200 focus:outline-none focus:border-indigo-500/50 placeholder-slate-650 transition-all"
                  />
                </div>
              </div>



              <button
                type="submit"
                disabled={loading}
                className="glow-btn w-full py-3.5 rounded-xl bg-gradient-to-r from-indigo-600 to-purple-600 hover:from-indigo-500 hover:to-purple-500 text-white font-bold text-xs shadow-xl shadow-indigo-600/10 flex items-center justify-center gap-2 group transition-all mt-2"
              >
                {loading ? (
                  <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
                ) : (
                  <>
                    <UserPlus className="w-3.5 h-3.5" />
                    Registrar e Ingresar
                  </>
                )}
              </button>
            </form>
          )}

          {/* Quick Access Card */}
          <div className="pt-4 border-t border-slate-850 text-center space-y-3">
            <span className="inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-md bg-indigo-500/10 text-[9px] font-bold text-indigo-400 tracking-wider uppercase">
              <Sparkles className="w-3 h-3" />
              Evaluación Rápida
            </span>
            <p className="text-[10px] text-slate-500 leading-relaxed">
              Haz clic en cualquiera de los botones para entrar instantáneamente con roles pre-configurados.
            </p>
            <div className="grid grid-cols-2 gap-3 pt-1">
              <button
                onClick={() => handleQuickLogin("admin")}
                disabled={loading}
                className="px-3.5 py-2.5 border border-purple-500/20 hover:border-purple-500/40 bg-purple-950/20 rounded-xl flex flex-col items-center gap-1 text-slate-300 hover:text-white transition-all group"
              >
                <Shield className="w-4 h-4 text-purple-400 group-hover:scale-110 transition-transform" />
                <span className="text-[10px] font-bold">Administrador</span>
                <span className="text-[8px] text-slate-500">Credenciales Admin</span>
              </button>

              <button
                onClick={() => handleQuickLogin("client")}
                disabled={loading}
                className="px-3.5 py-2.5 border border-indigo-500/20 hover:border-indigo-500/40 bg-indigo-950/20 rounded-xl flex flex-col items-center gap-1 text-slate-300 hover:text-white transition-all group"
              >
                <Users className="w-4 h-4 text-indigo-400 group-hover:scale-110 transition-transform" />
                <span className="text-[10px] font-bold">Cliente Seed</span>
                <span className="text-[8px] text-slate-500">Ana Gómez</span>
              </button>
            </div>
          </div>

        </div>
      </div>
    </main>
  );
}
